# Generated by Django 3.0.5 on 2020-12-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=30, unique=True)),
            ],
        ),
    ]
