# Generated by Django 3.0.5 on 2020-12-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_media', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
    ]
