# Generated by Django 3.0.5 on 2020-12-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_media', '0002_auto_20201213_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
