# Generated by Django 3.0.5 on 2020-12-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_media', '0004_auto_20201216_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(to='api_media.Genre'),
        ),
    ]
