# Generated by Django 3.0.5 on 2020-12-16 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_media', '0008_auto_20201216_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(3000)]),
        ),
    ]
