# Generated by Django 3.0.5 on 2020-12-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201214_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='yamdbuser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Код подтверждения'),
        ),
    ]
