# Generated by Django 3.0.5 on 2020-12-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='titles', to='api.Genre', verbose_name='Жанры'),
        ),
    ]
